#!/bin/bash

# you can specify any addition file same way and make a entry to template
export handle_user_data=`base64 -w 0 scripts/handle-user-data`

kickstart_file="centos-7-minimal.ks"

if [ -f "$kickstart_file" ] ; then
    rm $kickstart_file
fi

touch $kickstart_file

envsubst < centos-7-minimal.template > centos-7-minimal.ks

livecd-creator --config ./centos-7-minimal.ks --fslabel live-centos
